# Generated by Django 5.0.6 on 2025-03-11 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=25, unique=True)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('occupants', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('status', models.CharField(choices=[('Full', 'Full'), ('Not Full', 'Not full')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_pdf', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['PDF'])])),
                ('room_verification', models.CharField(max_length=200)),
            ],
        ),
    ]
