# Generated by Django 5.0.6 on 2025-03-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='user',
        ),
    ]
